name: flash_chat
description: Flash group chat app.
...
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.1
  cloud_firestore: ^3.4.2
  modal_progress_hud_nsn: ^0.2.1

flutter:
  uses-material-design: true
  assets:
    - images/